/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alma.aMazeZing.GUI;

import org.alma.aMazeZing.platform.ModuleLoader;

import org.alma.aMazeZing.core.Player;
import org.alma.aMazeZing.core.Core;
import org.alma.aMazeZing.plugins.UI;
import org.alma.aMazeZing.plugins.MapBuilder;
import org.alma.aMazeZing.history.History;
import org.alma.aMazeZing.quest.Quest;
import org.alma.aMazeZing.map.Map;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author cyrol
 */
public class GUI extends javax.swing.JFrame implements UI, Observer{

	private Map map;

    private Player p;

	private 	Core core;

	public void loadUI (Core c) {
		core = c;
		p = core.getPlayer();

		p.addObserver(this);
        this.p = p;

		initComponents();
				

		//updatePlayer
		//updateMap

		setVisible(true);

	}

	public void close(){
		setVisible(false);
	}


	@Override
    public void update (Observable o, Object arg) {
     	if (o instanceof Player) {
            printPlayer((Player) o);
        }
		else if (o instanceof Map){
			//print Map
		}
	}

	private void printPlayer (Player player) {

	}

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cblist_plugin = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        bt_charger = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A-MAZE-ZING");

       ModuleLoader ml = ModuleLoader.getInstance();
		 

        cblist_plugin.setModel(new javax.swing.DefaultComboBoxModel(ml.getPluginsForInterface(UI.class).toArray()));
        cblist_plugin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cblist_pluginItemStateChanged(evt);
            }
        });

        jLabel1.setText("UI:");

        bt_charger.setText("Charger");
        bt_charger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_chargerActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        jLabel2.setText("");
		
 		 jLabel3.setText("Quest :");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel( ml.getPluginsForInterface(MapBuilder.class).toArray() ));
         jLabel4.setText("History");
       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(ml.getPluginsForInterface(History.class).toArray() ));
       
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(bt_charger)
                        .addGap(248, 248, 248)
                        .addComponent(bt_annuler)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cblist_plugin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cblist_plugin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_charger)
                    .addComponent(bt_annuler)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cblist_pluginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cblist_pluginItemStateChanged
        // TODO add your handling code here:
      jLabel2.setText(cblist_plugin.getSelectedItem().toString());
    }//GEN-LAST:event_cblist_pluginItemStateChanged

    private void bt_chargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_chargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_chargerActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_annulerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_charger;
    private javax.swing.JComboBox cblist_plugin;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
